# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Updater_KYJG
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
HEADERS += ./Updater_KYJG.h
SOURCES += ./Updater_KYJG.cpp \
    ./main.cpp
FORMS += ./Updater_KYJG.ui
RESOURCES += Updater_KYJG.qrc
