# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = UpdateProgram
DESTDIR = ../x64/Release
CONFIG += release
RC_ICONS = MainIcon.ico
QMAKE_LFLAGS += /MANIFESTUAC:\"level=\'requireAdministrator\' uiAccess=\'false\'\"
RC_FILE = UpdateProgram.rc
LIBS += -L"."]
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
win32:RC_FILE = UpdateProgram.rc
HEADERS += ./resource.h \
    ./VersionNumber.h \
    ./UpdateProgram.h \
    ./Process7zWorker.h \
    ./UpdataModule.h \
    ../../InstallationPackage/TianLiInstallationPackage/QtWidgetsMessageBox2.h
SOURCES += ../../InstallationPackage/TianLiInstallationPackage/QtWidgetsMessageBox2.cpp \
    ./VersionNumber.cpp \
    ./Process7zWorker.cpp \
    ./UpdataModule.cpp \
    ./UpdateProgram.cpp \
    ./main.cpp
FORMS += ../../InstallationPackage/TianLiInstallationPackage/QtWidgetsMessageBox2.ui \
    ./UpdateProgram.ui
RESOURCES += ../../InstallationPackage/TianLiInstallationPackage/QtWidgetsMessageBox.qrc \
    UpdateProgram.qrc
